# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/docker-examples/README.md
#
# Look here for more config file examples:
# https://verdaccio.org/docs/en/best
#

## https://verdaccio.org/docs/configuration#storage
# path to a directory with all packages
storage: /verdaccio/storage/data

# path to a directory with plugins to include
plugins: /verdaccio/plugins

# https://verdaccio.org/docs/configuration/#max-body-size
max_body_size: 300mb

auth:
  # https://verdaccio.org/docs/en/plugin-auth
  # gitea-auth:
  #   # gitea-auth.url is not the api to the URl but just the server itself. Underneath we're concatenating /api/v1/user/orgs
  #   url: https://url-to-your-gitea-server
  #   # gitea-auth.defaultOrg If no orgs are in the list it defaults to ["gitea"]
  #   defaultOrg: gitea
  # htpasswd:
  #   file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

## Adit
# To use `npm audit` uncomment the following section
# Since: `verdaccio@3.0.0`
# npm audit is a new command released with npm 6.x. Verdaccio includes a built-in middleware plugin to handle this command.
middlewares:
  audit:
    enabled: true
  hello: # image 5.30+ support healthy check by: curl https://verdaccio.xxx/hello
    path: /hello # optional, default value is /hello
    text: ok # optional, default value is ok

# log settings
log:
  - { type: stdout, format: pretty, level: trace }
  #- {type: file, path: verdaccio.log, level: info}

# Since: [verdaccio@5.4.0](https://github.com/verdaccio/verdaccio/releases/tag/v5.4.0)
# Add default rate limit to user endpoints, npm token, npm profile, npm loding/adduser and login website to 100 request peer 15 min
userRateLimit:
  windowMs: 50000
  max: 100

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  enable: true
  title: npm for sinlov
  # logo:
  # comment out to disable gravatar support
  gravatar: true
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc  # 包的排序
  # darkMode: true # 黑暗模式
  # scope: "@scope"

# translate your registry, api i18n not available yet
i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
  web: en-US # 默认是en-US, 可改为中文 zh-CN

## a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  yarn:
    url: https://registry.yarnpkg.com/
  taobao:
    url: https://registry.npmmirror.com/